-- MySQL Script generated by MySQL Workbench
-- Tue Jan 29 13:10:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema RepasoPrueba
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RepasoPrueba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RepasoPrueba` DEFAULT CHARACTER SET utf8 ;
USE `RepasoPrueba` ;

-- -----------------------------------------------------
-- Table `RepasoPrueba`.`tbl_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepasoPrueba`.`tbl_categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombreCategoria` VARCHAR(45) NOT NULL,
  `descripcionCategoria` VARCHAR(200) NULL,
  `condicionCategoria` TINYINT NOT NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `idCategoria_UNIQUE` (`idCategoria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepasoPrueba`.`tbl_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepasoPrueba`.`tbl_producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `codigoProducto` VARCHAR(50) NOT NULL,
  `nombreProducto` VARCHAR(45) NOT NULL,
  `stockProducto` INT NOT NULL,
  `descripcionProducto` VARCHAR(200) NULL,
  `fotoProducto` VARCHAR(50) NULL,
  `estadoProducto` TINYINT NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  UNIQUE INDEX `idProducto_UNIQUE` (`idProducto` ASC),
  INDEX `fk_tbl_producto_tbl_categoria_idx` (`idCategoria` ASC),
  CONSTRAINT `fk_tbl_producto_tbl_categoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `RepasoPrueba`.`tbl_categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepasoPrueba`.`tbl_tipoPersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepasoPrueba`.`tbl_tipoPersona` (
  `idTipo` INT NOT NULL AUTO_INCREMENT,
  `tipoPersona` VARCHAR(45) NOT NULL,
  `descripcionTipoPersona` VARCHAR(200) NULL,
  PRIMARY KEY (`idTipo`),
  UNIQUE INDEX `idTipo_UNIQUE` (`idTipo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepasoPrueba`.`tbl_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepasoPrueba`.`tbl_persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombrePersona` VARCHAR(45) NOT NULL,
  `dpiPersona` VARCHAR(45) NOT NULL,
  `direccionPersona` VARCHAR(45) NULL,
  `emailPersona` VARCHAR(45) NULL,
  `telefonoPersona` VARCHAR(45) NOT NULL,
  `idTipo` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE INDEX `idPersona_UNIQUE` (`idPersona` ASC),
  INDEX `fk_tbl_persona_tbl_tipoPersona1_idx` (`idTipo` ASC),
  CONSTRAINT `fk_tbl_persona_tbl_tipoPersona1`
    FOREIGN KEY (`idTipo`)
    REFERENCES `RepasoPrueba`.`tbl_tipoPersona` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepasoPrueba`.`tbl_estadoIngreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepasoPrueba`.`tbl_estadoIngreso` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nombreEstado` VARCHAR(45) NOT NULL,
  `descripcionEstado` VARCHAR(200) NULL,
  PRIMARY KEY (`idEstado`),
  UNIQUE INDEX `idEstado_UNIQUE` (`idEstado` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepasoPrueba`.`tbl_ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepasoPrueba`.`tbl_ingreso` (
  `idIngreso` INT NOT NULL AUTO_INCREMENT,
  `tipocomprobanteIngreso` VARCHAR(45) NOT NULL,
  `seriecomprobanteIngreso` VARCHAR(45) NULL,
  `numcomprobanteIngreso` VARCHAR(45) NOT NULL,
  `fechahoraIngreso` DATETIME NOT NULL,
  `impuestoIngreso` DECIMAL(4,2) NOT NULL,
  `idPersona` INT NOT NULL,
  `idEstado` INT NOT NULL,
  PRIMARY KEY (`idIngreso`),
  UNIQUE INDEX `idIngreso_UNIQUE` (`idIngreso` ASC),
  INDEX `fk_tbl_ingreso_tbl_persona1_idx` (`idPersona` ASC),
  INDEX `fk_tbl_ingreso_tbl_estadoIngreso1_idx` (`idEstado` ASC),
  CONSTRAINT `fk_tbl_ingreso_tbl_persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `RepasoPrueba`.`tbl_persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_ingreso_tbl_estadoIngreso1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `RepasoPrueba`.`tbl_estadoIngreso` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepasoPrueba`.`tbl_detalleIngreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepasoPrueba`.`tbl_detalleIngreso` (
  `idDetalleIngreso` INT NOT NULL AUTO_INCREMENT,
  `idProducto` INT NOT NULL,
  `idIngreso` INT NOT NULL,
  `cantidadIngreso` INT NOT NULL,
  `preciocompraIngreso` DECIMAL(11,2) NOT NULL,
  `precioventaIngreso` DECIMAL(11,2) NOT NULL,
  INDEX `fk_tbl_producto_has_tbl_ingreso_tbl_ingreso1_idx` (`idIngreso` ASC),
  INDEX `fk_tbl_producto_has_tbl_ingreso_tbl_producto1_idx` (`idProducto` ASC),
  PRIMARY KEY (`idDetalleIngreso`),
  UNIQUE INDEX `idDetalleIngreso_UNIQUE` (`idDetalleIngreso` ASC),
  CONSTRAINT `fk_tbl_producto_has_tbl_ingreso_tbl_producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `RepasoPrueba`.`tbl_producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_producto_has_tbl_ingreso_tbl_ingreso1`
    FOREIGN KEY (`idIngreso`)
    REFERENCES `RepasoPrueba`.`tbl_ingreso` (`idIngreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepasoPrueba`.`tbl_estadoFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepasoPrueba`.`tbl_estadoFactura` (
  `idEstadoFactura` INT NOT NULL AUTO_INCREMENT,
  `nombreestadoFactura` VARCHAR(45) NOT NULL,
  `descripcionestadoFactura` VARCHAR(200) NULL,
  PRIMARY KEY (`idEstadoFactura`),
  UNIQUE INDEX `idEstadoFactura_UNIQUE` (`idEstadoFactura` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepasoPrueba`.`tbl_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepasoPrueba`.`tbl_factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `tipocomprobanteFactura` VARCHAR(45) NOT NULL,
  `seriecomprobanteFactura` VARCHAR(45) NOT NULL,
  `numerocomprobanteFactura` VARCHAR(45) NOT NULL,
  `fechahoraFactura` DATETIME NOT NULL,
  `impuestoFactura` DECIMAL(4,2) NOT NULL,
  `totalFactura` DECIMAL(11,2) NOT NULL,
  `idEstadoFactura` INT NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  UNIQUE INDEX `idFactura_UNIQUE` (`idFactura` ASC),
  INDEX `fk_tbl_factura_tbl_estadoFactura1_idx` (`idEstadoFactura` ASC),
  INDEX `fk_tbl_factura_tbl_persona1_idx` (`idPersona` ASC),
  CONSTRAINT `fk_tbl_factura_tbl_estadoFactura1`
    FOREIGN KEY (`idEstadoFactura`)
    REFERENCES `RepasoPrueba`.`tbl_estadoFactura` (`idEstadoFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_factura_tbl_persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `RepasoPrueba`.`tbl_persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepasoPrueba`.`tbl_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RepasoPrueba`.`tbl_detalle` (
  `idDetalle` INT NOT NULL AUTO_INCREMENT,
  `cantidadDetalle` INT NOT NULL,
  `precio` DECIMAL(11,2) NOT NULL,
  `descuento` DECIMAL(11,2) NOT NULL,
  `idFactura` INT NOT NULL,
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idDetalle`),
  UNIQUE INDEX `idDetalle_UNIQUE` (`idDetalle` ASC),
  INDEX `fk_tbl_detalle_tbl_factura1_idx` (`idFactura` ASC),
  INDEX `fk_tbl_detalle_tbl_producto1_idx` (`idProducto` ASC),
  CONSTRAINT `fk_tbl_detalle_tbl_factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `RepasoPrueba`.`tbl_factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_detalle_tbl_producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `RepasoPrueba`.`tbl_producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
